### ISSUE TITLE
Examples don't load nodes

### ISSUE THREAD

**Issue by lamachine** [luxonis/depthai-gui#1]
I hate to stars off as a newb, but I must have missed something basic.

Installed on Ubuntu, and have it running in a venv.  I can start PyFlow window with both the generic depthai-gui and with the file extension, but there is nothing in the graph window.  I tried using the load command, and it appears to work, but still no nodes.  Finally Add Custom button is active and I can open the dialog box, but by entering Cam, Camera, 1, etc. and then 1 and 2 or 1  or 0 and 1... matters not, I get warning dialog with list index is out of range.

I have the OAK-D running on the command line with all examples, etc.

**Comment by VanDavv** [comment]
Hi @lamachine 

Sorry for the trouble, it's on our roadmap to improve this tool. In the meantime, could you follow the steps visible below to open the node box? This should allow you to place new nodes onto the canvas

![instructions](https://user-images.githubusercontent.com/51138739/112560591-da98e080-8dd3-11eb-8d0d-64c4b5593849.png)

**Comment by VanDavv** [comment]
Closing the issue due to the new GUI introduction, feel free to update and give it a try.
Thanks for reporting, though!
