### ISSUE TITLE
Error when running depthai-gui

### ISSUE THREAD

**Issue by corlangerak** [luxonis/depthai-gui#3]
I keep getting these error windows when I run the depthai-gui command...
What should I do? I never see the depthai package in the GUI

<img width="432" alt="Screenshot 2021-03-26 at 01 33 27" src="https://user-images.githubusercontent.com/51138739/112560449-84c43880-8dd3-11eb-9d81-c09de59f67f1.png">

I hit Ok

<img width="432" alt="Screenshot 2021-03-26 at 01 36 08" src="https://user-images.githubusercontent.com/51138739/112560559-ca810100-8dd3-11eb-87b4-b22c7927dd83.png">
 
hit ok

<img width="432" alt="Screenshot 2021-03-26 at 01 36 19" src="https://user-images.githubusercontent.com/51138739/112560577-d40a6900-8dd3-11eb-8ee6-5c1e129fbf98.png">

hit ok

<img width="437" alt="Screenshot 2021-03-26 at 01 36 40" src="https://user-images.githubusercontent.com/51138739/112560591-da98e080-8dd3-11eb-8d0d-64c4b5593849.png">

**Comment by VanDavv** [comment]
Hi @corlangerak,
Are you maybe using Mac? I have not tested the `depthai-gui` there so it may be OS-related.
Could you try again and install the `depthai-gui` in the following way:
```
$ sudo apt-get install python3-venv
$ python3 -m venv gui_venv
$ source gui_venv/bin/activate
$ python3 -m pip install depthai-gui
$ depthai-gui
```

This will install the `depthai-gui` in a separate virtualenv and we'll be sure you're using latest gui release

**Comment by VanDavv** [comment]
Closing the issue due to the new GUI introduction, feel free to update and give it a try.
Thanks for reporting, though!
