### ISSUE TITLE
device not found error when using depthai-gui

### ISSUE THREAD

**Issue by vibhubithar** [luxonis/depthai-gui#4]
OS: Ubuntu 18.04
Kernel: 5.4.0-1-generic
System: x86_64 x86_64 x86_64 GNU/Linux
Device - OAK-D
I am able to run all the gen2 pipeline demos from the repo

But when using the pipeline builder event the most simple flow is failing as shown in the screenshots attached
![Screenshot from 2021-08-18 17-59-47](https://user-images.githubusercontent.com/10491706/130004831-764dc630-81d0-4f2f-8736-9aed77e6a25c.png)
![Screenshot from 2021-08-18 17-57-54](https://user-images.githubusercontent.com/10491706/130004838-bd93dcde-9549-4a7c-b260-2fb1a6310b55.png)
![Screenshot from 2021-08-18 17-55-00](https://user-images.githubusercontent.com/10491706/130004855-c07b04e4-1aa3-4292-b6e5-8d63c23511ff.png)

**Comment by VanDavv** [comment]
Hi @vibhubithar, thanks for the issue!
This repository was not updated in a while but I have it on my todo list to update it to a usable state soon. Main thing to update is DepthAI API integration, as this GUI was done on one of the early versions of Gen2 Pipeline Builder.

Sorry for the trouble, once the PR is ready I'll circle back here

**Comment by VanDavv** [comment]
Closing the issue due to the new GUI introduction, feel free to update and give it a try.
Thanks for reporting!
