### ISSUE TITLE
depthai-gui v2.0.4 - unexpected type 'PosixPath' 

### ISSUE THREAD

**Issue by jens-bongartz** [luxonis/depthai-gui#7]
Hello to everybody!

I am playing around with depthai-gui 2.0.4 on a Mac. I like the graphical view of the pipeline. As a beginner of DepthAI this gives be a much better understanding. But whenever I try to do some file action (open, save, import, etc.) the program crashes with the following error:

Traceback (most recent call last):
  File "/Users/bongartz/depthai-gui-master/NodeGraphQt/base/utils.py", line 216, in _save_session_as
    file_path = graph.save_dialog(current)
  File "/Users/bongartz/depthai-gui-master/NodeGraphQt/base/graph.py", line 1870, in save_dialog
    return self._viewer.save_dialog(current_dir, ext)
  File "/Users/bongartz/depthai-gui-master/NodeGraphQt/widgets/viewer.py", line 926, in save_dialog
    file_dlg = FileDialog.getSaveFileName(
  File "/Users/bongartz/depthai-gui-master/NodeGraphQt/widgets/dialogs.py", line 24, in getSaveFileName
    file_dlg = QtWidgets.QFileDialog.getSaveFileName(
TypeError: getSaveFileName(parent: QWidget = None, caption: str = '', directory: str = '', filter: str = '', initialFilter: str = '', options: Union[QFileDialog.Options, QFileDialog.Option] = 0): argument 3 has unexpected type 'PosixPath'
Abort trap: 6

I am far from being an expert in Python programming in general and NodeGraphQt in particular. So my quick and dirty workaround is to add the following after line 116 in the file depthai-gui-master/NodeGraphQt/base/utils.py 

115:  global default_file_path
116:  default_file_path = set_default_file_path
117:  default_file_path = '/users'

to set default_file_path to a defined string value. This works for me. Maybe someone can take look on this for a more general fix.

Best regards
Jens

**Comment by jens-bongartz** [comment]
I found the same behavior under Windows 10 which can be solved the same way as described above. Is there perhaps something wrong with the way I install depthai-gui?

Greetings
Jens

**Comment by VanDavv** [comment]
Hi @jens-bongartz, thanks for reporting the issue!

I found the bug, [pushed a fix to master](https://github.com/luxonis/depthai-gui/commit/b4d9555a1df943e7b65877f31ff47e1e1a522fc4), and released a new version - [`2.0.6`](https://pypi.org/project/depthai-gui/2.0.6/). Could you give it a try?

**Comment by jens-bongartz** [comment]
Hi @VanDavv, thanks for looking into the issue. Version 2.0.6 now works fine on my MacBook. I will try it tomorrow on my Windows 10 machine but I am expecting to get the same result. Thank you!

**Comment by jens-bongartz** [comment]
Quick Note: Version 2.0.6 doesn't show the bug on Windows 10 either. It works fine.

**Comment by VanDavv** [comment]
Thanks! Glad it worked
